services:
  linux-client:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: linux-client
    command: >
      sh -lc "ip route replace 172.31.0.0/24 via 172.30.0.254 &&
              sleep infinity"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      client-net:
        ipv4_address: 172.30.0.10
        interface_name: eth0
    volumes:
      - ./reports/captures:/captures

  linux-router:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: linux-router
    command: >
      sh -lc "sysctl -w net.ipv4.ip_forward=1 &&
              ip route &&
              sleep infinity"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    privileged: true
    networks:
      client-net:
        ipv4_address: 172.30.0.254
        interface_name: eth0
      server-net:
        ipv4_address: 172.31.0.254
        interface_name: eth1

  linux-server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: linux-server
    command: >
      sh -lc "ip route replace 172.30.0.0/24 via 172.31.0.254 &&
              iperf3 --server"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      server-net:
        ipv4_address: 172.31.0.10
        interface_name: eth0

networks:
  client-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
          gateway: 172.30.0.1
  server-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/24
          gateway: 172.31.0.1
